### ISSUE TITLE
Panics when database has xml data type

### ISSUE THREAD

**Issue by jasonjb82** [ivanceras/diwata#12]
I get this error when trying to connect to my postgres database
```
thread 'main' panicked at 'not yet handled: xml', /home/jbenedict/.cargo/registry/src/github.com-1ecc6299db9ec823/rustorm-0.10.7/src/pg/column_info.rs:320:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
This is what appears in the browser when I open http://localhost:8000
![image](https://user-images.githubusercontent.com/7259973/41183300-e2bd304c-6b2e-11e8-9182-113f00917582.png)

**Comment by ivanceras** [comment]
@jasonjb82 Thanks for filing an issue.
This looks like you are using `xml` data type which I haven't added an implementation yet. I will have to add xml type soon. Are there still other postgres data types that you are using that is not very common? I'm testing the project against the [sakila](https://github.com/ivanceras/sakila) database examples. If you have some more exotic data types that is not found in sakila database, you can list them here for me to add the implementation altogether.

**Comment by jasonjb82** [comment]
@ivanceras I just realised that I did not need the table that had the `xml` data type. However, after removing those tables, I noticed I have tables with `geom` data type that would probably not be supported as well. I have data in spatial formats which I have loaded to my db with PostGIS. Here's my ERD showing the data types that I have in my tables:

![palmdb_erd](https://user-images.githubusercontent.com/7259973/41184949-994b9296-6b38-11e8-95ea-f37a04bdd698.png)

This is the panic error I get:
```
error: invalid digit found in string when parsing range1 for data_type: "geometry(Point,4326)"
thread 'main' panicked at 'not yet handled: geometry', /home/jbenedict/.cargo/registry/src/github.com-1ecc6299db9ec823/rustorm-0.10.7/src/pg/column_info.rs:320:26
```
